Repository vocascan/vocascan-frontend, pull requests merged in 2021-05, with the labels that each got.

#56 Server input
  .prettierrc
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Form/TextInput/TextInput.scss
  src/Components/Indicators/LoadingIndicator/LoadingIndicator.jsx
  src/Components/Indicators/LoadingIndicator/LoadingIndicator.scss
  src/Components/Indicators/ServerValidIndicator/ServerValidIndicator.jsx
  src/Components/Indicators/ServerValidIndicator/ServerValidIndicator.scss
  src/Components/Layout/AuthenticatedLayout/AuthenticatedLayout.jsx
  src/Components/Layout/AuthenticatedLayout/AuthenticatedLayout.scss
  src/hooks/useDebounce.js
  src/i18n/locales/en/default.json
  src/screens/Login/Login.jsx
  src/screens/Login/Login.scss
  src/screens/Register/Register.jsx
  src/screens/Settings/Settings.jsx
  src/utils/api.js
  src/utils/constants.js
Labels: kind/dependencies, kind/enhancement, kind/ui

#57 added language selector
  src/Components/Form/Select/Select.jsx
  src/Components/LanguageSelector/LanguageSelector.jsx
  src/Components/Layout/UnauthenticatedLayout/UnauthenticatedLayout.jsx
  src/Components/Layout/UnauthenticatedLayout/UnauthenticatedLayout.scss
  src/Components/Modal/Modal.scss
  src/Forms/GroupForm/GroupForm.jsx
  src/Forms/PackageForm/PackageForm.jsx
  src/Forms/VocabForm/VocabForm.jsx
  src/hooks/useCountryFlag.js
  src/hooks/userCountryFlag.js
  src/i18n/I18nProvider.js
  src/i18n/locales/en/default.json
  src/redux/Actions/index.js
  src/redux/Actions/setting.js
  src/redux/Reducers/setting.js
  src/screens/Library/AllGroups/AllGroups.jsx
  src/screens/Library/AllPackages/AllPackages.jsx
  src/screens/Login/Login.scss
  src/screens/Register/Register.scss
  src/screens/Settings/Settings.jsx
Labels: kind/ui

#63 added language polish
  src/i18n/I18nProvider.js
Labels: kind/translations

#62 Language update
  package.json
  src/App.jsx
  src/Components/DirectionBox/DirectionBox.jsx
  src/Components/DirectionBox/DirectionBox.scss
  src/Components/Flag/Flag.jsx
  src/Components/Flag/Flag.scss
  src/Components/Flag/flags.png
  src/Components/Flag/language-country-map.js
  src/Components/Form/Select/Select.jsx
  src/Components/Form/Select/Select.scss
  src/Components/Form/Textarea/Textarea.jsx
  src/Components/Layout/UnauthenticatedLayout/UnauthenticatedLayout.jsx
  src/Components/Layout/UnauthenticatedLayout/UnauthenticatedLayout.scss
  src/Forms/GroupForm/GroupForm.jsx
  src/Forms/PackageForm/PackageForm.jsx
  src/hooks/useCountryFlag.js
  src/redux/Actions/index.js
  src/redux/Actions/language.js
  src/redux/Reducers/index.js
  src/redux/Reducers/language.js
  src/redux/Store/index.js
  src/screens/AddVocab/AddVocab.scss
  src/screens/Library/AllPackages/AllPackages.jsx
  src/screens/Library/AllPackages/AllPackages.scss
  src/screens/Login/Login.jsx
  src/screens/Register/Register.jsx
  src/utils/api.js
  src/utils/constants.js
  src/utils/index.js
Labels: kind/api, kind/ui

#64 Password reset
  src/i18n/locales/en/default.json
  src/screens/Profile/Profile.jsx
  src/utils/api.js
Labels: kind/enhancement

#65 added password input visibillity toggle
  src/Components/Form/TextInput/TextInput.jsx
  src/Components/Form/TextInput/TextInput.scss
Labels: kind/ui

#66 fix: dont redirect after reload
  src/App.jsx
  src/Components/Layout/CleanLayout/CleanLayout.jsx
  src/Components/Layout/CleanLayout/CleanLayout.scss
Labels: kind/bug

#60 End screen
  src/Components/Congratulation/Congratulation.jsx
  src/Components/Congratulation/Congratulation.scss
  src/Components/PackageOverview/PackageOverview.jsx
  src/Components/VocabCard/VocabCard.jsx
  src/Components/VocabCard/VocabCard.scss
  src/i18n/locales/en/default.json
  src/redux/Actions/index.js
  src/redux/Actions/learn.js
  src/redux/Actions/query.js
  src/redux/Reducers/index.js
  src/redux/Reducers/learn.js
  src/redux/Reducers/query.js
  src/screens/Learn/Dashboard/Dashboard.jsx
  src/screens/Learn/Dashboard/Dashboard.scss
  src/screens/Learn/Direction/Direction.jsx
  src/screens/Learn/End/End.jsx
  src/screens/Learn/End/End.scss
  src/screens/Learn/Learn.jsx
  src/screens/Learn/Query/Query.jsx
  src/screens/Learn/Query/Query.scss
  src/utils/index.js
Labels: kind/enhancement, kind/ui

#69 improved i18n
  src/i18n/locales/en/default.json
  src/screens/Custom/Custom.jsx
  src/screens/Progress/Progress.jsx
Labels: kind/translations

#70 fix: show username error
  src/i18n/locales/en/default.json
  src/screens/Register/Register.jsx
Labels: kind/enhancement, kind/ui

#68 about page
  package-lock.json
  package.json
  resources/electron.js
  src/App.jsx
  src/Components/ContributorCard/ContributorCard.jsx
  src/Components/ContributorCard/ContributorCard.scss
  src/Components/Counter/Counter.jsx
  src/Components/Counter/Counter.scss
  src/Components/Details/Details.jsx
  src/Components/Details/Details.scss
  src/Components/Flag/language-country-map.js
  src/Components/Nav/TopNav.jsx
  src/Components/Nav/TopNav.scss
  src/colors.scss
  src/i18n/locales/en/default.json
  src/screens/About/About.jsx
  src/screens/About/About.scss
  src/screens/Library/AllGroups/AllGroups.jsx
  src/screens/Library/AllPackages/AllPackages.jsx
  src/screens/Library/AllVocabs/AllVocabs.jsx
  src/utils/constants.js
Labels: kind/dependencies, kind/ui

#67 Update guide
  src/App.jsx
  src/Components/Button/Button.scss
  src/Components/Indicators/PageIndicator/PageIndicator.jsx
  src/Components/Indicators/PageIndicator/PageIndicator.scss
  src/Components/Modal/Modal.jsx
  src/Components/Modal/Modal.scss
  src/Components/SelectionBox/SelectionBox.jsx
  src/Components/SelectionBox/SelectionBox.scss
  src/Components/SlideShow/SlideShow.jsx
  src/Components/SlideShow/SlideShow.scss
  src/Forms/GroupForm/GroupForm.jsx
  src/Forms/GroupForm/GroupForm.scss
  src/Forms/PackageForm/PackageForm.jsx
  src/Forms/PackageForm/PackageForm.scss
  src/Forms/VocabForm/VocabForm.jsx
  src/Forms/VocabForm/VocabForm.scss
  src/colors.scss
  src/i18n/locales/en/default.json
  src/redux/Actions/index.js
  src/redux/Actions/login.js
  src/redux/Reducers/login.js
  src/screens/AddVocab/AddVocab.jsx
  src/screens/AddVocab/AddVocab.scss
  src/screens/FirstStartup/FirstStartup.jsx
  src/screens/FirstStartup/FirstStartup.scss
  src/screens/Guide/Guide.jsx
  src/screens/Guide/Guide.scss
  src/screens/Guide/Pages/End/End.jsx
  src/screens/Guide/Pages/End/End.scss
  src/screens/Guide/Pages/GroupDescription/GroupDescription.jsx
  src/screens/Guide/Pages/GroupDescription/GroupDescription.scss
  src/screens/Guide/Pages/GroupDescription/addGroup1.png
  src/screens/Guide/Pages/GroupDescription/addGroup2.png
  src/screens/Guide/Pages/PackageDescription/PackageDescription.jsx
  src/screens/Guide/Pages/PackageDescription/PackageDescription.scss
  src/screens/Guide/Pages/PackageDescription/addPackage1.png
  src/screens/Guide/Pages/PackageDescription/addPackage2.png
  src/screens/Guide/Pages/Start/Start.jsx
  src/screens/Guide/Pages/Start/Start.scss
  src/screens/Guide/Pages/VocabDescription/VocabDescription.jsx
  src/screens/Guide/Pages/VocabDescription/VocabDescription.scss
  src/screens/Guide/Pages/VocabDescription/addVocab.png
  src/screens/SelectionScreen/SelectionScreen.jsx
  src/screens/Settings/Settings.jsx
  src/screens/Settings/Settings.scss
Labels: kind/ui

#61 fix: added fixed logo files
  src/images/logo/color-rect.svg
  src/images/logo/color-round.svg
  src/images/logo/transparent-rect.svg
  src/images/logo/transparent-round.svg
  src/images/logo/vocascan-cloud.svg
  src/images/logo/vocascan-github-cover.png
  src/images/logo/vocascan-logo.png
  src/images/logo/vocascan-round-linux.png
  src/images/logo/vocascan-round-mac.png
  src/images/logo/vocascan-round-win.ico
  src/images/logo/vocascan-server-logo-small.png
  src/images/logo/vocascan-server-logo.png
  src/screens/SelectionScreen/SelectionScreen.jsx
Labels: kind/ui
