Repository vocascan/vocascan-frontend, pull requests merged in 2021-04, with the labels that each got.

#41 improved github workflow
  .github/pull_request_template.md
  .github/workflows/pullrequest.yml
Labels: enhancement

#44 added splash screen with update notification
  .gitignore
  package.json
  public/electron.js
  resources/electron.js
  resources/splash/splash-screen.css
  resources/splash/splash-screen.html
  resources/splash/splash-screen.js
  src/Components/Nav/TopNav.jsx
  src/Components/Nav/TopNav.scss
  src/Components/Nav/UpdateAvailable.jsx
  src/Components/Nav/UpdateAvailable.scss
  src/utils/index.js
Labels: kind/enhancement, kind/package

#46 improved menu and added about dialog
  .github/workflows/release.yml
  resources/electron.js
  resources/utils/constants.js
  resources/utils/ipc.js
  resources/utils/menu.js
  resources/utils/util.js
Labels: kind/enhancement, kind/github-actions

#43 working on create vocab
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Button/Button.jsx
  src/Components/Form/ArrayTextInput/ArrayTextInput.jsx
  src/Components/Form/ArrayTextInput/ArrayTextInput.scss
  src/Components/Form/Select/Select.jsx
  src/Components/Form/Select/Select.scss
  src/Components/Form/Switch/Switch.jsx
  src/Components/Form/Switch/Switch.scss
  src/Components/Form/TextInput/TextInput.jsx
  src/Components/Form/TextInput/TextInput.scss
  src/Components/Modal/Modal.jsx
  src/Components/Modal/Modal.scss
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavButton.jsx
  src/Components/Nav/NavButton.scss
  src/Components/Nav/TopNav.jsx
  src/Components/Nav/TopNav.scss
  src/Components/Select/Select.jsx
  src/Components/SelectionBox/SelectionBox.jsx
  src/Components/Snackbar/Snackbar.jsx
  src/Components/Snackbar/Snackbar.scss
  src/Components/Switch/Switch.jsx
  src/Components/TextInput/TextInput.jsx
  src/Components/Tooltip/Tooltip.jsx
  src/Components/Tooltip/Tooltip.scss
  src/Forms/GroupForm/GroupForm.jsx
  src/Forms/GroupForm/GroupForm.scss
  src/Forms/PackageForm/PackageForm.jsx
  src/Forms/PackageForm/PackageForm.scss
  src/Forms/VocabForm/VocabForm.jsx
  src/Forms/VocabForm/VocabForm.scss
  src/colors.scss
  src/context/SnackbarContext.jsx
  src/i18n/locales/en.json
  src/redux/Actions/form.js
  src/redux/Actions/index.js
  src/redux/Reducers/form.js
  src/redux/Reducers/index.js
  src/redux/Store/index.js
  src/screens/AddLanguagePackage/AddLanguagePackage.jsx
  src/screens/AddVocab/AddVocab.jsx
  src/screens/AddVocab/AddVocab.scss
  src/screens/FirstStartup/FirstStartup.jsx
  src/screens/Login/Login.jsx
  src/screens/Register/Register.jsx
  src/screens/SelectionScreen/SelectionScreen.jsx
  src/screens/Settings/Settings.jsx
  src/utils/api.js
  src/utils/constants.js
Labels: kind/enhancement, kind/ui

#45 initial react-table and allVocabs
  package.json
  src/App.jsx
  src/Components/Button/Button.scss
  src/Components/ConfirmDialog/ConfirmDialog.jsx
  src/Components/ConfirmDialog/ConfirmDialog.scss
  src/Components/Form/ArrayTextInput/ArrayTextInput.jsx
  src/Components/Form/Select/Select.jsx
  src/Components/Form/Switch/Switch.jsx
  src/Components/Layout/AuthenticatedLayout/AuthenticatedLayout.scss
  src/Components/Modal/Modal.jsx
  src/Components/Modal/Modal.scss
  src/Components/Nav/Nav.jsx
  src/Components/Nav/NavButton.jsx
  src/Components/Table/Table.jsx
  src/Components/Table/Table.scss
  src/Forms/GroupForm/GroupForm.jsx
  src/Forms/PackageForm/PackageForm.jsx
  src/Forms/VocabForm/VocabForm.jsx
  src/colors.scss
  src/hooks/useSnack.js
  src/i18n/locales/en.json
  src/index.scss
  src/redux/Actions/index.js
  src/redux/Actions/table.js
  src/redux/Reducers/index.js
  src/redux/Reducers/table.js
  src/redux/Store/index.js
  src/screens/AddVocab/AddVocab.jsx
  src/screens/FirstStartup/FirstStartup.jsx
  src/screens/Library/AllGroups/AllGroups.jsx
  src/screens/Library/AllGroups/AllGroups.scss
  src/screens/Library/AllPackages/AllPackages.jsx
  src/screens/Library/AllPackages/AllPackages.scss
  src/screens/Library/AllVocabs/AllVocabs.jsx
  src/screens/Library/AllVocabs/AllVocabs.scss
  src/screens/Library/Library.jsx
  src/screens/Library/Library.scss
Labels: kind/dependencies, kind/enhancement, kind/ui

#47 Profile screen
  package-lock.json
  src/App.jsx
  src/Components/ConfirmDialog/ConfirmDialog.jsx
  src/Components/StatsTable/StatsTable.jsx
  src/i18n/locales/en.json
  src/screens/Profile/Profile.jsx
  src/screens/Profile/Profile.scss
  src/utils/api.js
Labels: kind/enhancement, kind/ui

#50 refactored workflows
  .github/workflows/pullrequest.yml
  .github/workflows/translations.yml
  localazy.json
  package-lock.json
  package.json
  resources/electron.js
  resources/splash/splash-screen.html
  resources/splash/splash-screen.js
  src/i18n/I18nProvider.js
  src/i18n/locales/de.json
  src/i18n/locales/de/default.json
  src/i18n/locales/de/electron.json
  src/i18n/locales/en/default.json
  src/i18n/locales/en/electron.json
  src/i18n/locales/fr.json
  src/i18n/locales/locales.json
Labels: kind/github-actions, kind/translations

#52 chore: use new country flags plugin in forms and tables
  src/Components/DirectionBox/DirectionBox.scss
  src/Components/Form/Select/Select.jsx
  src/Components/Form/Select/Select.scss
  src/Forms/GroupForm/GroupForm.jsx
  src/Forms/PackageForm/PackageForm.jsx
  src/Forms/VocabForm/VocabForm.jsx
  src/hooks/userCountryFlag.js
  src/screens/AddVocab/AddVocab.scss
  src/screens/Library/AllGroups/AllGroups.jsx
  src/screens/Library/AllPackages/AllPackages.jsx
  src/screens/Library/AllPackages/AllPackages.scss
Labels: kind/enhancement, kind/ui

#53 Issuetemplates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  README.md
Labels: kind/enhancement

#51 Dashboard
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Button/Button.scss
  src/Components/DirectionBox/DirectionBox.jsx
  src/Components/DirectionBox/DirectionBox.scss
  src/Components/Form/Select/Select.jsx
  src/Components/Form/Select/Select.scss
  src/Components/Nav/Nav.jsx
  src/Components/PackageOverview/PackageOverview.jsx
  src/Components/PackageOverview/PackageOverview.scss
  src/Forms/GroupForm/GroupForm.jsx
  src/Forms/PackageForm/PackageForm.jsx
  src/Forms/VocabForm/VocabForm.jsx
  src/hooks/userCountryFlag.js
  src/i18n/locales/en/default.json
  src/i18n/locales/en/electron.json
  src/redux/Actions/index.js
  src/redux/Actions/learn.js
  src/redux/Reducers/index.js
  src/redux/Reducers/learn.js
  src/screens/AddVocab/AddVocab.scss
  src/screens/Learn/Dashboard/Dashboard.jsx
  src/screens/Learn/Dashboard/Dashboard.scss
  src/screens/Learn/Direction/Direction.jsx
  src/screens/Learn/Direction/Direction.scss
  src/screens/Learn/Learn.jsx
  src/screens/Learn/Learn.scss
  src/screens/Library/AllGroups/AllGroups.jsx
  src/screens/Library/AllPackages/AllPackages.jsx
  src/screens/Library/AllPackages/AllPackages.scss
  src/utils/api.js
  src/utils/constants.js
Labels: kind/enhancement, kind/ui
