Repository vocascan/vocascan-frontend, pull requests merged in 2022-06, with the labels that each got.

#111 Theme system
  Dockerfile
  docker/generate-config.js
  package-lock.json
  package.json
  public/config.js
  public/default-themes/dark.css
  public/default-themes/light.css
  src/App.jsx
  src/Components/Form/Select/Select.scss
  src/Components/Form/TextInput/TextInput.scss
  src/Components/Form/Textarea/Textarea.scss
  src/Components/Modal/Modal.scss
  src/Components/Nav/NavButton.scss
  src/Components/Nav/TopNav.scss
  src/Components/SelectionBox/SelectionBox.scss
  src/Components/ThemeSelector/ThemeSelector.jsx
  src/Components/VocabCard/VocabCard.scss
  src/colors.scss
  src/config.js
  src/hooks/useTheme.js
  src/i18n/locales/en/default.json
  src/index.scss
  src/redux/Actions/index.js
  src/redux/Actions/setting.js
  src/redux/Reducers/setting.js
  src/screens/Login/Login.scss
  src/screens/Register/Register.scss
  src/screens/Settings/Settings.jsx
  src/utils/constants.js
  src/utils/index.js
Labels: kind/enhancement

#116 email verification popup
  src/App.jsx
  src/Components/Button/Button.jsx
  src/i18n/locales/en/default.json
  src/index.js
  src/screens/Auth/EmailVerify/EmailVerify.jsx
  src/screens/Auth/EmailVerify/EmailVerify.scss
  src/screens/Auth/Login/Login.jsx
  src/screens/Auth/Login/Login.scss
  src/screens/Auth/Register/Register.jsx
  src/screens/Auth/Register/Register.scss
  src/screens/Login/Login.jsx
  src/screens/Register/Register.jsx
  src/utils/api.js
Labels: kind/enhancement

#117 About page update
  public/default-themes/dark.css
  public/default-themes/light.css
  src/Components/ContributorCard/ContributorCard.jsx
  src/Components/ContributorCard/ContributorCard.scss
  src/colors.scss
  src/i18n/locales/en/default.json
  src/screens/About/About.jsx
  src/utils/constants.js
Labels: kind/enhancement, priority/medium

#121 Fix env-variable overrides
  public/config.js
  src/config.js
Labels: kind/bug
