Repository vocascan/vocascan-frontend, pull requests merged in 2022-01, with the labels that each got.

#81 Frontend restructure
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/ci.yml
  .github/workflows/pullrequest.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/translations.yml
  .prettierrc
  CHANGELOG.md
  Dockerfile
  Dockerfile.ci
  README.md
  docker/docker-compose.yml
  docker/generate-config.js
  docker/nginx.conf
  localazy.json
  package-lock.json
  package.json
  public/config.js
  public/index.html
  public/logo.svg
  resources/electron.js
  resources/splash/splash-screen.css
  resources/splash/splash-screen.html
  resources/splash/splash-screen.js
  resources/utils/constants.js
  resources/utils/ipc.js
  resources/utils/menu.js
  resources/utils/util.js
  src/App.jsx
  src/Components/Indicators/ServerValidIndicator/ServerValidIndicator.jsx
  src/Components/InviteCode/InviteCode.jsx
  src/Components/Nav/TopNav.jsx
  src/Components/Nav/UpdateAvailable.jsx
  src/config.js
  src/hooks/useFeature.js
  src/i18n/locales/de/electron.json
  src/i18n/locales/en/default.json
  src/i18n/locales/en/electron.json
  src/i18n/locales/pl/electron.json
  src/i18n/locales/ru/electron.json
  src/index.js
  src/modules/clipboard.js
  src/modules/fileOperations.js
  src/modules/update.js
  src/screens/Library/AllGroups/AllGroups.jsx
  src/screens/Library/AllPackages/AllPackages.jsx
  src/screens/Login/Login.jsx
  src/screens/Register/Register.jsx
  src/utils/api.js
  src/utils/index.js
Labels: kind/enhancement, priority/high, reviewed/skip-check

#82 fix translations workflow
  .github/workflows/translations.yml
Labels: kind/bug

#83 fix translations again
  .github/workflows/translations.yml
Labels: kind/bug

#84 fix translations again
  .github/workflows/translations.yml
Labels: kind/bug

#86 Precompile react on main push
  .github/workflows/ci.yml
Labels: kind/enhancement, kind/github-actions

#85 Feat: Legal updates
  src/Components/Nav/Nav.jsx
  src/Components/Nav/Nav.scss
  src/hooks/useLinkCreator.js
  src/i18n/locales/en/default.json
  src/screens/Register/Register.jsx
  src/screens/Register/Register.scss
  src/utils/api.js
  src/utils/constants.js
Labels: kind/enhancement, kind/translations, priority/medium

#87 Feat: cookie consent
  package.json
  src/App.jsx
  src/Components/CookieConsentBanner/CookieConsentBanner.jsx
  src/Components/CookieConsentBanner/CookieConsentBanner.scss
  src/i18n/locales/en/default.json
Labels: kind/enhancement, kind/dependencies, priority/medium

#88 style: added icon for frontend
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/index.js
Labels: kind/enhancement, priority/low

#92 fix: remove untranslated languages
  src/i18n/I18nProvider.js
Labels: kind/bug, priority/high

#91 fix: removed fancy menu style
  src/Components/Nav/Nav.jsx
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavButton.jsx
  src/Components/Nav/NavButton.scss
  src/i18n/locales/en/default.json
  src/redux/Actions/index.js
  src/redux/Actions/setting.js
  src/redux/Reducers/setting.js
  src/screens/Settings/Settings.jsx
Labels: kind/enhancement, priority/high

#93 fixed translations
  localazy.json
  src/i18n/locales/de/electron.json
  src/i18n/locales/pl/electron.json
  src/i18n/locales/ru/electron.json
Labels: kind/bug, kind/translations, priority/high, reviewed/skip-check

#95 fixed flags in firefox
  src/Components/Flag/Flag.jsx
  src/Components/Flag/Flag.scss
  src/Components/Flag/language-country-map.js
  src/Components/Form/Select/Select.scss
  src/screens/Library/AllPackages/AllPackages.scss
Labels: kind/bug, priority/high

#96 Fix/translations
  src/Components/SelectionBox/SelectionBox.jsx
  src/Forms/VocabForm/VocabForm.jsx
Labels: kind/bug, kind/translations

#98 fix linebreaks on vocab card and vocab table
  src/Components/VocabCard/VocabCard.jsx
  src/index.scss
  src/screens/Library/AllVocabs/AllVocabs.jsx
Labels: kind/bug

#97 Password complexity
  src/Components/Indicators/PasswordComplexityIndicator/PasswordComplexityIndicator.jsx
  src/Components/Indicators/PasswordComplexityIndicator/PasswordComplexityIndicator.scss
  src/colors.scss
  src/i18n/locales/en/default.json
  src/screens/Login/Login.scss
  src/screens/Profile/Profile.jsx
  src/screens/Register/Register.jsx
  src/screens/Register/Register.scss
  src/utils/index.js
Labels: kind/enhancement

#100 v1.2.1
  CHANGELOG.md
  package.json
  src/Components/Flag/Flag.jsx
  src/Components/Flag/Flag.scss
  src/Components/Flag/language-country-map.js
  src/Components/Form/Select/Select.scss
  src/Components/Indicators/PasswordComplexityIndicator/PasswordComplexityIndicator.jsx
  src/Components/Indicators/PasswordComplexityIndicator/PasswordComplexityIndicator.scss
  src/Components/SelectionBox/SelectionBox.jsx
  src/Components/VocabCard/VocabCard.jsx
  src/Forms/VocabForm/VocabForm.jsx
  src/colors.scss
  src/i18n/locales/de/default.json
  src/i18n/locales/en/default.json
  src/index.scss
  src/screens/Library/AllPackages/AllPackages.scss
  src/screens/Library/AllVocabs/AllVocabs.jsx
  src/screens/Login/Login.scss
  src/screens/Profile/Profile.jsx
  src/screens/Register/Register.jsx
  src/screens/Register/Register.scss
  src/utils/index.js
Labels: reviewed/skip-check
